#!/bin/sh
set -e

# Create a runtime configuration file that sets Vite environment variables
cat > /app/dist/runtime-config.js << EOF
// Runtime configuration - generated by docker-entrypoint.sh
window.env = window.env || {};
window.env.VITE_API_BASE_URL = "${VITE_API_BASE_URL:-http://localhost:4000}";
EOF

# Execute the original entrypoint
exec "$@"
